team7-chill-guys/mono-repo

com.sparta.logistics.eureka-server/src/main/java/com/sparta/logistics/eureka_server/EurekaServerApplication.java, com.sparta.logistics.eureka-server/src/main/resources/application.properties
* **as-is**
* 유레카 서버 없음.
* **to-be**
* 유레카 서버 생성됨
eureka server application.yml 생성
* 관련 자료 링크
=> ✨ feat[#6] : eureka server create

com.sparta.logistics.company-service/src/main/java/com/sparta/logistics/company_service/controller/CompanyController.java, com.sparta.logistics.company-service/src/main/java/com/sparta/logistics/company_service/dto/CompanyDeleteDto.java, com.sparta.logistics.company-service/src/main/java/com/sparta/logistics/company_service/dto/CompanyRequestDto.java, com.sparta.logistics.company-service/src/main/java/com/sparta/logistics/company_service/dto/CompanyResponseDto.java, com.sparta.logistics.company-service/src/main/java/com/sparta/logistics/company_service/dto/CompanySearchDto.java, com.sparta.logistics.company-service/src/main/java/com/sparta/logistics/company_service/dto/CompanyUpdateDto.java
* [] 코드 작성 가이드라인을 준수했는가?
* **as-is**
* company 이슈만 발행
* **to-be**
* DTO&Controller 생성
* 현재 상태로 CRUD&Search 테스트 가능
* docker와 env 파일이 ignore되지 않아서 수동으로 체크해서 올리지 않음
* 효율성을 위해 조회 & 등록 로직을 변경할 예정
* 깃 테스트 커밋은 무시
* 관련 자료 링크
=> feat[#2] : company Dto&Controller create

com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/controller/ProductController.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/dto/RequestProductCreateDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/dto/RequestProductUpdateDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/dto/ResponseProductCreateDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/dto/ResponseProductDeleteDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/dto/ResponseProductGetDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/dto/ResponseProductSearchDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/dto/ResponseProductUpdateDto.java
* **as-is**
* 변경 사항 없음
* **to-be**
* 상품 DTO, Controller 추가
* 더미 데이터로 CRUD와 Search 기능을 구현하였습니다. 상품 생성 시 상품 업체, 상품 담당 허브 확인 여부는 비즈니스 로직에서 구현할 예정입니다. DTO와 Controller에 구성된 내용이 잘 작성되었는지 확인 부탁드립니다.
* 관련 자료 링크
=> ✨ feat[#5]: 상품 서비스 DTO, Controller 추가

com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/controller/OrderController.java, com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/dto/OrderCreateRequestDto.java, com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/dto/OrderCreateResponseDto.java, com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/dto/OrderDeleteResponseDto.java, com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/dto/OrderDetailResponseDto.java, com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/dto/OrderListResponseDto.java, com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/dto/OrderUpdateRequestDto.java
* **as-is**
* order 브랜치만 생성
* **to-be**
* DTO&Controller 생성
* CRUD&Search 테스트 완료
* 관련 자료 링크
=> ✨ feat[#14] : 주문 Dto, Controller 추가

com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/request/DeliveryCreateRequestDto.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/request/DeliveryRouteUpdateRequestDto.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/request/DeliveryUpdateRequestDto.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/response/DeliveryResponseDto.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/response/DeliveryRouteResponseDto.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/response/PageResponseDto.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/mapper/DeliveryMapper.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/mapper/DeliveryRouteMapper.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/model/BaseTimeEntity.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/model/Delivery.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/model/DeliveryRoute.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/model/DeliveryRouteStatus.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/model/DeliveryStatus.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/model/Distance.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/model/RecipientCompany.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/model/Time.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/model/converter/DistanceConverter.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/model/converter/TimeConverter.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/infrastructure/config/JpaConfig.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/presentation/DelieveryController.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/presentation/DeliveryRouteController.java
* **as-is**
* **to-be**
* 관련 자료 링크
=> ✨ feat[#1]: 배송, 배송경로기록 Dto, Controller 구현

com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/application/dto/response/UserSearchMeResponseDto.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/application/service/UserService.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/presentation/controller/UserController.java
* **as-is**
* user data 요청시 더미 데이터 반환
* **to-be**
* userId, username으로 user 검색 기능 추가
* 헤더에 넣어둔 X-User-Id로 userId를 가져와 본인 조회하는 기능 추가
* 모든 서비스로 연결되는 헤더에 로그인한 user 정보가 포함될 예정입니다.
* X-User-Id = userId
* X-User-Name = username
* X-User-Role = role
* 원하시는 부분 추출하여 사용하시거나 전체 데이터가 필요할 경우 api/users/search 요청으로 받아오시면 됩니다.
* 입력받는 값이 양식에 맞거나 Null 체크하는 부분을 컨트롤러에 넣었는데 해당 부분이 컨트롤러에 있어도 되는지 의견 부탁드리겠습니다.
* 관련 자료 링크
=> ✨ feat[#9] 유저 조회 기능 추가

com.sparta.logistics.delivery-service/build.gradle, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/mock/HubRouteInfoDto.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/mock/OrderInfoDto.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/mock/ProductInfoDto.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/request/DeliveryRouteUpdateRequestDto.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/request/DeliveryUpdateRequestDto.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/response/DeliveryResponseDto.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/response/DeliveryRouteResponseDto.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/mapper/DeliveryMapper.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/mapper/DeliveryRouteMapper.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/DeliveryRouteService.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/DeliveryService.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/ExtractRegion.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/RegionService.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/mock/MockDeliveryManager.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/mock/MockHubRouteService.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/mock/MockOrderService.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/mock/MockProductService.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/model/Delivery.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/model/DeliveryRoute.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/model/DeliveryStatus.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/repository/DeliveryRepository.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/repository/DeliveryRouteRepository.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/presentation/DelieveryController.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/presentation/DeliveryRouteController.java
* **as-is**
* **to-be**
* 관련 자료 링크
=> ✨ feat [#32] : 배송 / 배송경로기록 기능 구현

com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/UserServiceApplication.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/application/dto/request/UserPasswordUpdateRequestDto.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/application/dto/request/UserUpdateRequestDto.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/application/dto/response/UserUpdateResponseDto.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/application/service/AuthService.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/application/service/UserService.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/domain/entity/User.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/global/BaseEntity.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/presentation/controller/AuthController.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/presentation/controller/UserController.java
* **as-is**
* 회원가입, 로그인, 조회 기능만 존재
* **to-be**
* 유저 수정, 탈퇴 기능 추가
* 관련 자료 링크
=> ✨ feat[#9] : 비밀번호 수정, 유저 수정, 유저 탈퇴 기능 구현

com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/DeliveryServiceApplication.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/mock/HubRouteInfoDto.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/request/DeliveryCreateRequestDto.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/DeliveryAssignmentScheduler.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/DeliveryRouteService.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/DeliveryService.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/mock/MockCompanyService.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/mock/MockDeliveryManagerService.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/mock/MockHubRouteService.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/repository/DeliveryRepository.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/repository/DeliveryRouteRepository.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/presentation/DelieveryController.java
* **as-is**
* **to-be**
* 관련 자료 링크
=> 🩹 fix [#46] : 담당자 배정 로직 수정

com.sparta.logistics.ai-service/Dockerfile-ai, com.sparta.logistics.company-service/Dockerfile-company, com.sparta.logistics.config-server/Dockerfile-config, com.sparta.logistics.delivery-manager-service/Dockerfile-delivery-manager, com.sparta.logistics.delivery-service/Dockerfile-delivery, com.sparta.logistics.eureka-server/Dockerfile-eureka, com.sparta.logistics.gateway/Dockerfile-gateway, com.sparta.logistics.hub-service/Dockerfile-hub, com.sparta.logistics.order-service/Dockerfile-order, com.sparta.logistics.product-service/Dockerfile-product, com.sparta.logistics.slack-service/Dockerfile-slack, com.sparta.logistics.user-service/Dockerfile-user
* **as-is**
* 로컬에서 테스트.
* **to-be**
* 도커 파일로 컨테이너 생성 후 도커 환경에서 테스트 환경 구성
* 관련 자료 링크
=> ✨ feat [#59] : 도커 환경 구성을 위한 도커 파일 추가.

com.sparta.logistics.company-service/build.gradle, com.sparta.logistics.company-service/src/main/java/com/sparta/logistics/company_service/CompanyServiceApplication.java, com.sparta.logistics.company-service/src/main/java/com/sparta/logistics/company_service/application/service/CompanyService.java, com.sparta.logistics.company-service/src/main/java/com/sparta/logistics/company_service/presentation/controller/CompanyController.java
* **as-is**
* **to-be**
* 관련 자료 링크
=> ✨feat [#63] : 배송에게 업체 HubId 전달

com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/application/dto/request/OrderCreateRequestDto.java, com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/application/dto/request/OrderUpdateRequestDto.java, com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/application/dto/response/OrderDetailResponseDto.java, com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/application/service/OrderService.java, com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/domain/Order.java, com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/infrastructure/client/dto/request/OrderDeliveryRequestDto.java
* **as-is**
* 주문 필드 누락
* **to-be**
* 객체 생성 entity로 이동
* OrderDelivery 수정
* 관련 자료 링크
=> ♻️ refactor [#57] 주문 필드 추가 및 OrderDelivery 수정

com.sparta.logistics.hub-service/build.gradle, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/HubServiceApplication.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/global/entity/BaseEntity.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/application/dto/mock/DataLoader.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/application/dto/response/HubDetailResponseDto.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/application/dto/response/HubListResponseDto.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/application/service/HubService.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/application/service/HubServiceImpl.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/presentation/controller/HubController.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/dto/request/HubRouteCreateRequestDto.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/dto/request/HubRouteUpdateRequestDto.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/dto/response/HubRouteCreateResponseDto.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/dto/response/HubRouteDetailResponseDto.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/dto/response/HubRouteListResponseDto.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/dto/response/HubRouteUpdateResponseDto.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/dto/response/KakaoResponseDto.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/service/HubRouteService.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/service/HubRouteServiceImpl.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/service/KakaoMapApiServiceImpl.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/service/KakaoMapService.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/domain/entity/HubRoute.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/domain/repository/HubRouteRepository.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/presentation/controller/HubRouteController.java
* **as-is**
- 허브 루트 생성시 모든 데이터 직접 입력
* **to-be**
- 카카오맵을 이용한 이동시간, 이동거리 조회 후 허브 루트 생성
- 이동시간, 이동거리 타입변경
- 이동경로 검색시 반환 형식 변경
- 이동경로 검색시 검색 키워드 필드 변경
* 관련 자료 링크
=> ✨ feat[#44] 허브 루트 생성 및 허브 루트 검색 리팩토링

com.sparta.logistics.delivery-manager-service/build.gradle, com.sparta.logistics.delivery-manager-service/src/main/java/com/sparta/logistics/delivery_service/DeliveryManagerServiceApplication.java, com.sparta.logistics.delivery-manager-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/request/DeliveryManagerUpdateRequestDto.java, com.sparta.logistics.delivery-manager-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/response/DeliveryManagerInfoDto.java, com.sparta.logistics.delivery-manager-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/response/DeliveryManagerResponseDto.java, com.sparta.logistics.delivery-manager-service/src/main/java/com/sparta/logistics/delivery_service/application/mapper/DeliveryManagerInfoMapper.java, com.sparta.logistics.delivery-manager-service/src/main/java/com/sparta/logistics/delivery_service/application/mapper/DeliveryManagerMapper.java, com.sparta.logistics.delivery-manager-service/src/main/java/com/sparta/logistics/delivery_service/application/service/DeliveryManagerService.java, com.sparta.logistics.delivery-manager-service/src/main/java/com/sparta/logistics/delivery_service/domain/model/DeliveryManager.java, com.sparta.logistics.delivery-manager-service/src/main/java/com/sparta/logistics/delivery_service/domain/repository/DeliveryManagerRepository.java, com.sparta.logistics.delivery-manager-service/src/main/java/com/sparta/logistics/delivery_service/presentation/DeliveryManagerController.java
* **as-is**
* **to-be**
* Feign Client 설정 추가
* sequence 타입 Integer -> Long 변경
* 배송담당자 배정 엔드포인트 구현
* 배송담당자 배정 비지니스 로직 구현
* 출발HubId와 타입으로 적절한 배송담당자 조회하는 쿼리
* 최대 순번 조회하는 쿼리
* 관련 자료 링크
=> ✨ feat [#55] : DeliveryManager 반환 로직 구현

com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/application/service/HubService.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/application/service/HubServiceImpl.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/presentation/controller/HubController.java
* **as-is**
* hubName, address 로 검색
* **to-be**
* hubName, address, hubId 로 검색
* 관련 자료 링크
=> ✨ feat[#72]: hubId로 허브 정보 검색 기능 추가

com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/application/dto/request/OrderCreateRequestDto.java, com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/application/dto/request/OrderUpdateRequestDto.java, com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/application/service/OrderService.java, com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/domain/Order.java, com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/presentation/controller/OrderController.java
* **as-is**
* 
* **to-be**
* 사용자 정보 로직 추가
* entity 수정
* 관련 자료 링크
=> ✨feat [#71] : 주문 사용자 정보 로직 추가

com.sparta.logistics.ai-service/build.gradle, com.sparta.logistics.ai-service/src/main/resources/application.properties, com.sparta.logistics.product-service/build.gradle, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/application/dto/request/ProductStockRequestDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/application/dto/response/StockUpdateResponseDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/application/service/ProductService.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/client/CompanyClient.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/client/dto/CompanyResponseDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/client/dto/HubResponseDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/domain/entity/Product.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/presentation/controller/ProductController.java, com.sparta.logistics.product-service/src/main/resources/application.properties
* **as-is**
* **to-be**
* AI 서비스 build.gradle 수정
* 관련 자료 링크
=> 🩹 fix[#90]: AI 서비스 build.gradle 수정

com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/global/entity/BaseEntity.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/application/service/HubService.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/application/service/HubServiceImpl.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/domain/entity/Hub.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/presentation/controller/HubController.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/service/HubRouteService.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/service/HubRouteServiceImpl.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/service/KakaoMapApiServiceImpl.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/service/KakaoMapService.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/domain/entity/HubRoute.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/presentation/controller/HubRouteController.java
* **as-is**
* 임시 아이디 사용
* 삭제된 데이터도 함께 조회
* **to-be**
* 헤더에서 아이디 값 받아와서 사용
* 삭제된 데이터를 제외하고 조회
* 관련 자료 링크
=>  feat[#82] : header에서 아이디 조회 및 삭제된 데이터 조회

com.sparta.logistics.company-service/src/main/java/com/sparta/logistics/company_service/application/dto/request/CompanyCreateRequestDto.java, com.sparta.logistics.company-service/src/main/java/com/sparta/logistics/company_service/application/dto/request/CompanyUpdateRequestDto.java, com.sparta.logistics.company-service/src/main/java/com/sparta/logistics/company_service/application/dto/response/CompanyDetailResponseDto.java, com.sparta.logistics.company-service/src/main/java/com/sparta/logistics/company_service/application/service/CompanyService.java, com.sparta.logistics.company-service/src/main/java/com/sparta/logistics/company_service/domain/Company.java, com.sparta.logistics.company-service/src/main/java/com/sparta/logistics/company_service/presentation/controller/CompanyController.java
* **as-is**
* 
* **to-be**
* 업체 사용자 정보 로직 추가
* @Setter 삭제
* 관련 자료 링크
=> ✨feat [#86] : 업체 사용자 정보 로직 추가

.gitignore
* **as-is**
* **to-be**
* 관련 자료 링크
=> 🙈 gitfix [#99] : 도커 테스트를 위해 application.yml 해제

com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/application/dto/response/UserRoleSearchResponseDto.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/application/service/HubServiceImpl.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/infrastructure/Client/UserClient.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/dto/request/HubRouteCreateRequestDto.java, com.sparta.logistics.hub-service/src/main/resources/application.yml
* **as-is**
* **to-be**
- FeignClient 설정 추가
* 관련 자료 링크
=> ✨feat[#102]: 허브 - 유저 FeignClient 설정 추가

com.sparta.logistics.company-service/src/main/resources/application.yml, com.sparta.logistics.order-service/src/main/resources/application.yml
* **as-is**
* **to-be**
* 관련 자료 링크
=> [add] 통합테스트를 위합 yml 업로드

com.sparta.logistics.delivery-service/src/main/resources/application.yml
* **as-is**
* **to-be**
* 관련 자료 링크
=> delivery-service application.yml

com.sparta.logistics.delivery-manager-service/src/main/resources/application.yml
* **as-is**
* **to-be**
* 관련 자료 링크
=> delivery-manager-service application.yml

com.sparta.logistics.ai-service/src/main/resources/application.yml, com.sparta.logistics.eureka-server/src/main/resources/application.yml, com.sparta.logistics.gateway/src/main/resources/application.yml, com.sparta.logistics.product-service/src/main/resources/application.yml, com.sparta.logistics.user-service/src/main/resources/application.yml
* **as-is**
* **to-be**
* 관련 자료 링크
=> add: yml 파일 추가

com.sparta.logistics.slack-service/src/main/java/com/sparta/logistics/slack_service/application/service/SlackService.java, com.sparta.logistics.slack-service/src/main/java/com/sparta/logistics/slack_service/infrastructure/client/SlackClient.java
* **as-is**
* **to-be**
* 관련 자료 링크
=> 🩹 fix: 슬랙 value 네이밍 변경

com.sparta.logistics.ai-service/src/main/java/com/sparta/logistics/ai_service/application/service/AiService.java, com.sparta.logistics.ai-service/src/main/java/com/sparta/logistics/ai_service/infrastructure/client/GeminiClient.java
* **as-is**
* **to-be**
* 관련 자료 링크
=> 🩹 fix: AI value 네이밍 변경

com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/HubServiceApplication.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/global/config/RestTemplateConfig.java, com.sparta.logistics.hub-service/src/main/resources/application.yml
* **as-is**
* env 파일을 못가져오는 문제
* **to-be**
* env 파일 경로 지정
* 관련 자료 링크
=> 🐛 bugfix [#114] : env 파일 경로 지정

com.sparta.logistics.delivery-service/build.gradle, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/DeliveryAssignmentScheduler.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/DeliveryRouteService.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/DeliveryService.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/model/BaseTimeEntity.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/infrastructure/client/HubRouteClient.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/infrastructure/config/JpaConfig.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/presentation/DelieveryController.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/presentation/DeliveryRouteController.java, com.sparta.logistics.delivery-service/src/main/resources/application.yml
* **as-is**
* **to-be**
* 관련 자료 링크
=> 🩹 fix[#113]: Request Header로 사용자아이디 받기 및 오류 수정

com.sparta.logistics.ai-service/src/main/resources/application.yml
* **as-is**
* **to-be**
* 관련 자료 링크
=> 🩹 fix: AI yml 파일 수정

com.sparta.logistics.slack-service/src/main/resources/application.yml
* **as-is**
* **to-be**
* 관련 자료 링크
=> 🩹 fix: 슬랙 yml 파일 수정

com.sparta.logistics.gateway/src/main/resources/application.yml
* **as-is**
* 마스터 권한 라우팅 없음
* **to-be**
* 마스터 권한으로 접속하는 URL 경로 추가
* 관련 자료 링크
=> ♻️ refactor[#3] : master 권한 기능 라우팅 추가.

com.sparta.logistics.slack-service/src/main/java/com/sparta/logistics/slack_service/application/service/SlackService.java, com.sparta.logistics.slack-service/src/main/java/com/sparta/logistics/slack_service/infrastructure/client/SlackClient.java, com.sparta.logistics.slack-service/src/main/resources/application.yml
* **as-is**
* **to-be**
* 관련 자료 링크
=> 🐛 bugfix: 통합 테스트 슬랙 오타 수정

com.sparta.logistics.ai-service/src/main/resources/application.yml
* **as-is**
* **to-be**
* 관련 자료 링크
=> 🐛 bugfix: 통합 테스트 상품 yml 파일 수정

com.sparta.logistics.hub-service/build.gradle, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/dto/response/HubRouteListResponseDto.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/service/HubRouteServiceImpl.java, com.sparta.logistics.hub-service/src/main/resources/application.yml
* **as-is**
* **to-be**
* 허브 루트 정보 캐싱처리
* yml 수정
* 관련 자료 링크
=> ✨ feat [#94] : 허브루트 캐싱 추가

com.sparta.logistics.delivery-manager-service/src/main/resources/application.yml, com.sparta.logistics.delivery-service/build.gradle, com.sparta.logistics.delivery-service/src/main/resources/application.properties, com.sparta.logistics.delivery-service/src/main/resources/application.yml
* **as-is**
* **to-be**
* 관련 자료 링크
=> 배송/배송담당자 application.yml 수정

com.sparta.logistics.slack-service/src/main/resources/application.yml
* **as-is**
* **to-be**
* 관련 자료 링크
=> 🩹 fix: 통합 테스트 슬랙 yml 파일 수정

com.sparta.logistics.ai-service/src/main/resources/application.yml
* **as-is**
* **to-be**
* 관련 자료 링크
=> 🩹 fix: 통합 테스트 AI yml 파일 수정

com.sparta.logistics.company-service/src/main/resources/application.yml, com.sparta.logistics.order-service/src/main/resources/application.yml
* **as-is**
* 
* **to-be**
* 
* 주문 application.yml도 업체라고 명시에서 커밋했습니다. 참고 부탁드립니다!
* 관련 자료 링크
=> 🩹 fix [#133]: 업체&주문 application yml 파일 재수정

com.sparta.logistics.gateway/src/main/resources/application.yml
* **as-is**
* master 경로가 명세에 맞지 않음
* **to-be**
*  user-service 마스터 경로 /user -> /users
*  hub-service 마스터 경로 /hub -> /hubs
* 관련 자료 링크
=> 🩹 fix[#3] : application.yml 오탈자 수정

com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/global/entity/BaseEntity.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/application/service/HubServiceImpl.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/service/HubRouteServiceImpl.java
* **as-is**
* **to-be**
* 삭제 로직에 @Transactional 어노테이션 추가
- 이미 삭제된 허브의 중복 삭제 요청 시 예외 처리 추가
- BaseEntity에 softDelete(), isDeleted() 메서드 추가
* 관련 자료 링크
=> ♻️ refactor[#145]: 허브 논리적 삭제(Soft Delete) 로직 개선

com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/application/dto/request/DeliveryManagerUpdateRequestDto.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/application/dto/response/UserSearchAllResponseDto.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/application/service/UserService.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/config/CustomPageable.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/config/WebConfig.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/domain/entity/User.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/domain/repository/UserRepository.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/infrastructure/jpa/UserJpaRepository.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/infrastructure/repository/UserRepositoryImpl.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/presentation/controller/UserController.java, com.sparta.logistics.user-service/src/main/java/com/sparta/logistics/user_service/presentation/feignClient/DeliveryManagerFeignClient.java
* **as-is**
* 페이지네이션 미적용. 
* 유저 전체 조회 없음. 
* 배송 담당자 권한을 가지고 있는 유저 수정시 배송 담당자 테이블 업데이트 없음.
* **to-be**
* 페이지네이션 적용.
* 유저 전체조회 기능 추가
* 배송 담당자 권한을 가지고 있는 유저 수정시 배송 담당자 서비스의 배송 담당자 수정 기능 호출
* 적용된 사항에 대해서는 커밋 메세지 설명란에 자세히 적어두었습니다.
* 관련 자료 링크
=> ✨ feat[#9] : user-service 페이지네이션 적용, 전체조회 기능 추가, 배송 담당자 업데이트 트리거 로직 수정

com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/mapper/DeliveryInfoMapper.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/DeliveryService.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/ProducerService.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/infrastructure/messaging/config/ProducerApplicationKafkaConfig.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/infrastructure/messaging/dto/DeliveryInfoDto.java
* **as-is**
* **to-be**
* 슬랙서비스로 보낼 dto를 infra 패키지로 이동
* 메세지 내용에 주소 추가
* 관련 자료 링크
=> 🚚 move : DeliveryInfoDto를 infrastructure 패키지 이동

com.sparta.logistics.delivery-manager-service/src/main/java/com/sparta/logistics/delivery_service/application/service/DeliveryManagerService.java, com.sparta.logistics.delivery-manager-service/src/main/java/com/sparta/logistics/delivery_service/domain/model/DeliveryManager.java, com.sparta.logistics.delivery-manager-service/src/main/java/com/sparta/logistics/delivery_service/presentation/DeliveryManagerController.java
* **as-is**
* **to-be**
* 슬랙 아이디 변경 엔드포인트, 서비스로직 추가
* 관련 자료 링크
=> ✨ feat[#141]: slack id 수정 기능 추가

com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/application/dto/request/ProductCreateRequestDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/application/dto/request/ProductStockRequestDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/application/dto/request/ProductUpdateRequestDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/application/dto/response/ProductCreateResponseDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/application/dto/response/ProductGetResponseDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/application/dto/response/ProductSearchResponseDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/application/dto/response/ProductUpdateResponseDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/application/dto/response/StockUpdateResponseDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/application/service/ProductService.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/domain/entity/Product.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/infrastructure/client/CompanyClient.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/infrastructure/client/HubClient.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/infrastructure/client/dto/response/CompanyDetailResponseDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/infrastructure/client/dto/response/HubDetailResponseDto.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/presentation/controller/ProductController.java, com.sparta.logistics.product-service/src/main/resources/application.yml
* **as-is**
* **to-be**
* 관련 자료 링크
=> ✨ feat[#148]: 상품 전체 조회 기능 추가

com.sparta.logistics.gateway/src/main/java/com/sparta/logistics/gateway/security/config/SecurityConfig.java, com.sparta.logistics.gateway/src/main/resources/application.yml
* **as-is**
* 권한 별 경로 설정 없음
* **to-be**
* 권한 별 경로 설정.
* 
* 관련 자료 링크
=> ✨ feat[#3] : 권한별 접근 경로 제한

com.sparta.logistics.slack-service/src/main/java/com/sparta/logistics/slack_service/infrastructure/config/ConsumerApplicationKafkaConfig.java
* **as-is**
* **to-be**
* 관련 자료 링크
=> 🩹 fix[#158]: delivery 파일 패키지 경로 수정

com.sparta.logistics.company-service/src/main/java/com/sparta/logistics/company_service/application/service/CompanyService.java, com.sparta.logistics.company-service/src/main/java/com/sparta/logistics/company_service/infrastructure/client/HubClient.java, com.sparta.logistics.company-service/src/main/java/com/sparta/logistics/company_service/infrastructure/client/dto/request/CompanyHubRequestDto.java, com.sparta.logistics.order-service/src/main/java/com/sparta/logistics/order_service/application/service/OrderService.java, com.sparta.logistics.product-service/src/main/resources/application.yml
* **as-is**
* 
* **to-be**
* product의 application.yml 수정
* 상품 등록시 존재하는 허브아이디에만 등록 가능하도록 수정
* 배송 실패하면 상품 재고 롤백
* 관련 자료 링크
=> ✨ feat[#133] : 상품 등록시 허브 존재여부 확인 & 배송 실패시 롤백 기능

com.sparta.logistics.ai-service/src/main/java/com/sparta/logistics/ai_service/infrastructure/dto/request/GeminiRequestDto.java
* **as-is**
* **to-be**
* 관련 자료 링크
=> 🩹 fix[#160]: AI 필요한 어노테이션 추가

com.sparta.logistics.slack-service/src/main/java/com/sparta/logistics/slack_service/infrastructure/config/ConsumerApplicationKafkaConfig.java
* **as-is**
* **to-be**
* 관련 자료 링크
=> 🩹 fix: config 수정

com.sparta.logistics.hub-service/build.gradle, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/global/config/CacheConfig.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/global/utils/JwtUtil.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/application/service/HubServiceImpl.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/infrastructure/Client/UserClient.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/presentation/controller/HubController.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/presentation/controller/MasterHubController.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/service/HubRouteService.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/application/service/HubRouteServiceImpl.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/presentation/controller/HubRouteController.java, com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hubroute/presentation/controller/MasterHubRouteController.java, com.sparta.logistics.hub-service/src/main/resources/application.yml
* **as-is**
* **to-be**
* 마스터 권한 전용 컨트롤러 분리
* 권한에 따른 URL 구조 개선 (/api/master/**)
* JWT 토큰에서 사용자 정보(userId, username 등) 파싱하여 활용
* FeignClient의 반환 타입을 List → Page 로 변경
* 관련 자료 링크
=> ♻️ refactor[#144] : 허브, 허브루트 마스터 권한 API 경로 변경

com.sparta.logistics.hub-service/src/main/java/com/sparta/logistics/hub_service/hub/application/dto/mock/DataLoader.java
* **as-is**
* **to-be**
*  isNull 에서 equals 로 변경
* 관련 자료 링크
=>  🩹 fix[#168]: 허브 mock 데이터 자동 생성 안되는 오류 발생

com.sparta.logistics.gateway/src/main/java/com/sparta/logistics/gateway/security/config/SecurityConfig.java, com.sparta.logistics.gateway/src/main/resources/application.yml
* **as-is**
* 상품 서비스와 상품 서비스의 마스터 경로를 중복 매핑
* **to-be**
* 상품 서비스와 마스터 경로 아이디 값 변경
* 관련 자료 링크
=> 🩹fix[#170] : 게이트 웨이 application.yml 오탈자 수정

com.sparta.logistics.slack-service/src/main/java/com/sparta/logistics/slack_service/application/dto/request/SlackMessageSendRequestDto.java, com.sparta.logistics.slack-service/src/main/java/com/sparta/logistics/slack_service/application/service/SlackService.java, com.sparta.logistics.slack-service/src/main/java/com/sparta/logistics/slack_service/infrastructure/client/AiClient.java, com.sparta.logistics.slack-service/src/main/java/com/sparta/logistics/slack_service/presentation/controller/SlackController.java
* **as-is**
* **to-be**
* 관련 자료 링크
=> 🩹fix[#172] : 슬랙서비스 수정

com.sparta.logistics.delivery-manager-service/build.gradle, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/DeliveryService.java
* **as-is**
* **to-be**
* 관련 자료 링크
=> 🩹fix[#172] : 배송담당자 배정 타입 HUB로 변경 / 배송담당자 의존성 수정

com.sparta.logistics.delivery-manager-service/src/main/java/com/sparta/logistics/delivery_service/application/service/DeliveryManagerService.java, com.sparta.logistics.delivery-manager-service/src/main/java/com/sparta/logistics/delivery_service/domain/model/BaseTimeEntity.java, com.sparta.logistics.delivery-manager-service/src/main/java/com/sparta/logistics/delivery_service/infrastructure/config/JpaConfig.java, com.sparta.logistics.delivery-manager-service/src/main/java/com/sparta/logistics/delivery_service/presentation/DeliveryManagerController.java
* **as-is**
* **to-be**
* 관련 자료 링크
=> ✨ feat[#172] : 배송담당자 JpaAuditing 추가

com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/application/service/ProductService.java, com.sparta.logistics.product-service/src/main/java/com/sparta/logistics/product_service/domain/entity/Product.java
* **as-is**
* **to-be**
* 관련 자료 링크
=> ♻️ refactor[#179]: 상품 리팩토링

com.sparta.logistics.ai-service/src/main/java/com/sparta/logistics/ai_service/application/service/AiService.java
* **as-is**
* **to-be**
* 더 구체적인 내용으로 응답하도록 요청 메시지를 변경하였습니다.
* 관련 자료 링크
=> ♻️ refactor[#183]: AI 리팩토링

com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/request/DeliveryUpdateRequestDto.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/dto/response/DeliveryResponseDto.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/mapper/DeliveryMapper.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/application/service/DeliveryService.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/domain/model/Delivery.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/infrastructure/messaging/dto/DeliveryInfoDto.java, com.sparta.logistics.delivery-service/src/main/java/com/sparta/logistics/delivery_service/infrastructure/messaging/dto/DeliveryInfoMapper.java
* **as-is**
* **to-be**
* DeliveryInfoDto 수정 : 상품아이디(productId) 추가
* Delivery 엔티티에 상품아이디(productId) 추가
* 관련 자료 링크
=> 🩹 fix[#156] : 슬랙서비스로 보낼 메세지 내용 추가
